document.documentElement.classList.add('js');
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),header=document.querySelector('.site-header'),menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-nav');
function closeMenu(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','打开导航');menu.querySelector('span').textContent='＋';nav.classList.remove('open');}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'关闭导航':'打开导航');menu.querySelector('span').textContent=open?'−':'＋';nav.classList.toggle('open',open);});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});document.addEventListener('click',e=>{if(!header.contains(e.target))closeMenu();});matchMedia('(min-width: 761px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{if(isIntersecting){target.classList.add('visible');revealObserver.unobserve(target);}}),{threshold:.08,rootMargin:'0px 0px -18px 0px'});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));document.querySelectorAll('.numbers,.editorial-strip,.ability-types,.personality-words').forEach(group=>[...group.children].forEach((el,i)=>el.style.setProperty('--delay',`${i%3*100}ms`)));
const chapters=[...document.querySelectorAll('.chapter')],parallax=[...document.querySelectorAll('.parallax')],path=document.querySelector('.ability-path');let queued=false;
function updateScroll(){queued=false;let current=chapters[0];for(const s of chapters)if(s.getBoundingClientRect().top<innerHeight*.32)current=s;header.classList.toggle('dark',current.dataset.theme==='dark');nav.querySelectorAll('a').forEach(a=>{if(a.hash===`#${current.id}`)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});if(!reduced.matches){parallax.forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom>-150&&r.top<innerHeight+150){const off=Math.max(-22,Math.min(22,(innerHeight*.5-r.top-r.height*.5)*Number(el.dataset.speed)));el.style.translate=`0 ${off}px`;}});if(path){const r=path.getBoundingClientRect();path.style.setProperty('--progress',`${Math.max(0,Math.min(100,(innerHeight-r.top)/(innerHeight+r.height)*140))}%`);}}}
function schedule(){if(!queued){queued=true;requestAnimationFrame(updateScroll);}}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);reduced.addEventListener('change',()=>{if(reduced.matches)parallax.forEach(el=>el.style.translate='');schedule();});updateScroll();
const desk=document.querySelector('.work-desk'),workButtons=[...document.querySelectorAll('[data-focus]')];let pinned=null;function focusPaper(key){desk.classList.toggle('has-focus',!!key);document.querySelectorAll('[data-paper]').forEach(p=>p.classList.toggle('selected',p.dataset.paper===key));}
workButtons.forEach(button=>{button.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')focusPaper(button.dataset.focus);});button.addEventListener('pointerleave',()=>focusPaper(pinned));button.addEventListener('focus',()=>focusPaper(button.dataset.focus));button.addEventListener('blur',()=>focusPaper(pinned));button.addEventListener('click',()=>{pinned=pinned===button.dataset.focus?null:button.dataset.focus;workButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.focus===pinned)));focusPaper(pinned);if(pinned&&innerWidth<=760)document.querySelector(`[data-paper="${pinned}"]`).scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'center'});});});
const dialog=document.querySelector('.lightbox');let opener=null;document.querySelectorAll('[data-lightbox]').forEach(button=>button.addEventListener('click',()=>{opener=button;const img=button.querySelector('img');dialog.querySelector('img').src=img.src;dialog.querySelector('img').alt=img.alt;document.querySelector('#lightbox-caption').textContent=button.dataset.caption;dialog.showModal();document.body.classList.add('lightbox-open');}));dialog.querySelector('.lightbox-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});dialog.addEventListener('close',()=>{document.body.classList.remove('lightbox-open');opener?.focus({preventScroll:true});});
document.querySelector('#copy-email').addEventListener('click',async()=>{const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText('fengzihui0225@163.com');status.textContent='邮箱已复制。期待下一次相遇。';}catch{status.textContent='请复制邮箱：fengzihui0225@163.com';}});document.querySelector('.life-reel')?.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();e.currentTarget.scrollBy({left:e.key==='ArrowRight'?300:-300,behavior:reduced.matches?'instant':'smooth'});}});
