const workNotes=[
 {title:'产品与行业调研',lead:'先理解产品解决什么问题，再把技术能力写成具体行业能够理解的内容。',sections:[['我承担的工作','围绕 AI 销售培训、会话智能等产品开展资料调研，整理产品能力与行业场景，参与行业案例和解决方案类内容制作。'],['如何组织信息','从业务场景、客户痛点、产品能力与应用方式四个方面整理资料。关注酒店、物业等行业的具体需求，避免只罗列技术名词。'],['对应的工作产出','产品与行业资料整理、行业案例及解决方案类内容。研究工作为后续文案写作提供信息依据。']],sample:'行业场景 → 客户需求 → 对应产品能力 → 内容表达',caption:'依据实习职责整理的工作思路，非企业原稿截图',reflection:'这段工作让我学会先问“内容写给谁、解决什么问题”，再决定文章结构和信息取舍。'},
 {title:'品牌与内容传播',lead:'将企业技术、产品与客户案例组织为清楚、可读的对外内容。',sections:[['我承担的工作','参与世界人工智能大会（WAIC）、Multi-Agent 研究成果及客户合作案例等主题的资料调研、稿件撰写、修改与发布，支持企业品牌与技术成果传播。'],['内容怎样推进','先整理事件背景和可核对的资料，再组织稿件结构与重点；根据反馈修改措辞、内容顺序和表达方式，配合完成排版与发布。'],['对应的工作产出','企业活动传播稿、技术成果相关稿件及客户案例内容。这里展示的是内容支持职责，不代表本人到场参会或负责企业参展。']],sample:'资料整理 / 初稿撰写 / 反馈修改 / 排版发布',caption:'根据现有简历及工作记录整理的工作环节',reflection:'技术内容需要兼顾准确与可读。先讲清应用背景，再解释能力与价值，能够帮助不同背景的读者理解。'},
 {title:'SEO 与 AI 内容实践',lead:'让内容生产兼顾搜索需求、渠道特点和清楚的表达。',sections:[['SEO 与多渠道分发','参与关键词资料整理、SEO 文章撰写、多平台发布及搜索排名跟踪，涉及头条、百家号、腾讯、一点资讯和官网等渠道。'],['Prompt 测试与优化','使用 DeepSeek、豆包、腾讯元宝辅助资料整理及内容生成，围绕标题、结构、篇幅和品牌植入调整提示词，迭代内容生产方法。'],['人工检查与修改','AI 生成后继续检查信息依据、表达重复与行业称呼，结合文章用途调整内容。未提供完整流量及转化数据，因此不填增长比例。']],sample:'明确关键词与场景 → 调整标题及结构 → 生成初稿 → 人工核对修改 → 发布与搜索表现跟踪',caption:'依据实习内容整理的方法说明，非效果数据',reflection:'工具可以帮助组织初稿，但内容的准确性、场景贴合程度与最终质量仍需要人工判断。'}
];
const workDialog=document.querySelector('#intern-dialog');let workIndex=0,workOpener;
function showWorkNote(index){workIndex=(index+workNotes.length)%workNotes.length;const n=workNotes[workIndex];workDialog.querySelector('.note-count').textContent=`WORK NOTES / 0${workIndex+1}`;workDialog.querySelector('.intern-dialog-body').innerHTML=`<h2 id="intern-note-title">${n.title}</h2><p class="note-lead">${n.lead}</p>${n.sections.map((s,i)=>`<section class="note-section"><h3>0${i+1} / ${s[0]}</h3><p>${s[1]}</p></section>`).join('')}<div class="note-sample"><small>${n.caption}</small>${n.sample}</div><section class="note-section"><h3>这段实践的收获</h3><p>${n.reflection}</p></section><div class="note-nav"><button data-note-prev>← 上一本</button><button data-note-next>下一本 →</button></div>`;workDialog.scrollTop=0;workDialog.querySelector('[data-note-prev]').onclick=()=>showWorkNote(workIndex-1);workDialog.querySelector('[data-note-next]').onclick=()=>showWorkNote(workIndex+1);}
document.querySelectorAll('[data-work-note]').forEach(button=>button.addEventListener('click',()=>{workOpener=button;showWorkNote(Number(button.dataset.workNote));workDialog.showModal();document.body.classList.add('intern-dialog-open')}));
workDialog.querySelector('.intern-close').onclick=()=>workDialog.close();workDialog.addEventListener('close',()=>{document.body.classList.remove('intern-dialog-open');workOpener?.focus({preventScroll:true})});workDialog.addEventListener('click',event=>{if(event.target!==workDialog)return;const r=workDialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)workDialog.close()});
